import type { Context } from "hono";
import type { DB, DbSchema, Dialect } from "./db";
import type { Role } from "@shared/types";

/**
 * Runtime bindings. `Env` is generated by `wrangler types` (worker-configuration.d.ts)
 * and contains HYPERDRIVE, LINKS_KV, ASSETS and APP_URL. Secrets are added here.
 */
export interface AppBindings extends Env {
  SESSION_SECRET: string;
  IP_HASH_SALT: string;
  /** One-time bootstrap token gating the first-run installer (`POST /api/setup`). */
  SETUP_TOKEN: string;
  /** Cloudflare D1 binding, present only when DB_DRIVER="d1" (otherwise absent
   *  from the generated Env, so it's declared optional here). DB_DRIVER itself
   *  comes from the generated Env (a wrangler var). Cloudflare-for-SaaS custom
   *  domain credentials live in settings (configured via /admin), not env. */
  DB?: D1Database;
}

export interface SessionUser {
  id: string;
  email: string;
  role: Role;
}

export interface AppVariables {
  db: DB;
  schema: DbSchema;
  dialect: Dialect;
  user: SessionUser | null;
  sessionId: string | null;
}

export type AppEnv = { Bindings: AppBindings; Variables: AppVariables };
export type AppContext = Context<AppEnv>;
